### ISSUE TITLE
吊炸天啊

### ISSUE THREAD

**Issue by SilentTTxo** [nobodxbodon/zhconverter#7]
老哥你竟然代码也是用中文写的，不得不佩服！

**Comment by nobodxbodon** [comment]
讨论组里有其他的项目也是用中文代码: 
https://github.com/program-in-chinese/Python
https://github.com/program-in-chinese/Java
还有刚发现的汉化TypeScript项目https://github.com/dotnet/csharplang/issues/993#issuecomment-336716860, 也是用的中文代码

**Comment by modowei** [comment]
用汉字有点别扭啦，想用，最后还是弃了……
