### ISSUE TITLE
叶字转繁体失败

### ISSUE THREAD

**Issue by jcchentb** [nobodxbodon/zhconverter#8]
如叶问，中文对繁体中key存在空格。

**Comment by nobodxbodon** [comment]
多谢反馈. 已在https://github.com/program-in-chinese/zhconverter/commit/9d1bdd1ce1136f92ecf5ef0499376459fd1ae8d7#diff-3ec0186d2877915e532f35aae5424925 添加测试用例, 但好像'叶问'转换是正确的. 不知您是对单词进行转换还是全文/句转换? 如果是后者, 能否把全句帖一下?

**Comment by jcchentb** [comment]
不好意思，好像是我版本获取有误，该问题在新版本已修复，叶字被转换为恭

**Comment by nobodxbodon** [comment]
哦, 应该是上个版本的问题: https://github.com/nobodxbodon/zhconverter/issues/5. 
我该把readme写得更明白的, 这个库已经不是[最新的](https://github.com/program-in-chinese/zhconverter)了
